# Usa node:slim como imagen base, ya que node:alpine puede presentar problemas con algunas dependencias.
FROM node:22.13-slim AS builder

WORKDIR /app

# Copia el package.json y package-lock.json e instala las dependencias
COPY package.json package-lock.json ./
RUN npm install

# Copia el resto del código fuente y construye el frontend
COPY . .
RUN npm run build

# Montamos el frontend en nginx
FROM nginx:latest

# Copia los archivos estáticos generados en "build" a Nginx
# Sobreescribe la configuración por defecto de nginx.
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Expone el puerto 80 (donde se ejecuta Nginx)
EXPOSE 80

# Comando para ejecutar Nginx
CMD ["nginx", "-g", "daemon off;"]
