# Usa node:slim como imagen base, ya que node:alpine puede presentar problemas con algunas dependencias.
FROM node:22.13-slim

WORKDIR /app

# Copia el package.json y package-lock.json e instala las dependencias
COPY package.json package-lock.json ./
RUN npm install

# Copia el resto del código fuente y construye el frontend
COPY . .
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]