services:
  backend:
    build: ./backend
    env_file: ./backend/.env.backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend

  db:
    container_name: database
    image: postgres:17
    env_file: ./backend/.env.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static:
  media: